name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
      
      - name: Build the app
        run: npm run build
      
      - name: Deploy build folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true

  enable-pages:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Enable GitHub Pages via API
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.updateInformationAboutPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              source: {
                branch: "gh-pages",
                path: "/"
              }
            });
